/**************************************************************************************************
 * Copyright (c) 2021 Calypso Networks Association https://calypsonet.org/                        *
 *                                                                                                *
 * See the NOTICE file(s) distributed with this work for additional information regarding         *
 * copyright ownership.                                                                           *
 *                                                                                                *
 * This program and the accompanying materials are made available under the terms of the Eclipse  *
 * Public License 2.0 which is available at http://www.eclipse.org/legal/epl-2.0                  *
 *                                                                                                *
 * SPDX-License-Identifier: EPL-2.0                                                               *
 **************************************************************************************************/

#pragma once

#include <cstdint>
#include <map>
#include <memory>
#include <vector>

/* Calypsonet Terminal Calypso */
#include "CalypsoCard.h"
#include "SvDebitLogRecord.h"
#include "SvLoadLogRecord.h"
#include "SvOperation.h"

/* Keyple Card Calypso */
#include "AbstractApduCommand.h"
#include "AbstractCardCommand.h"
#include "CalypsoCardClass.h"

/* Keyple Core Util */
#include "LoggerFactory.h"

namespace keyple {
namespace card {
namespace calypso {

using namespace calypsonet::terminal::calypso::card;
using namespace calypsonet::terminal::calypso::transaction;
using namespace keyple::core::util::cpp;

using StatusProperties = AbstractApduCommand::StatusProperties;

/**
 * (package-private)<br>
 * Builds the SV Get command.
 *
 * @since 2.0.1
 */
class CmdCardSvGet final : public AbstractCardCommand {
public:
    /**
     * (package-private)<br>
     * Instantiates a new CmdCardSvGet.
     *
     * @param calypsoCardClass the card class.
     * @param calypsoCard the Calypso card.
     * @param svOperation the desired SV operation.
     * @throw IllegalArgumentException If the command is inconsistent
     * @since 2.0.1
     */
    CmdCardSvGet(const CalypsoCardClass calypsoCardClass,
                 const std::shared_ptr<CalypsoCard> calypsoCard,
                 const SvOperation svOperation);

    /**
     * {@inheritDoc}
     *
     * @return False
     * @since 2.0.1
     */
    bool isSessionBufferUsed() const override;

    /**
     * {@inheritDoc}
     *
     * @since 2.0.1
     */
    CmdCardSvGet& setApduResponse(const std::shared_ptr<ApduResponseApi> apduResponse) override;

    /**
     * (package-private)<br>
     * Gets the command header used to build the prepared "load/debit/undebit" SAM commands
     *
     * @return A byte array containing the header data
     * @since 2.0.1
     */
    const std::vector<uint8_t>& getSvGetCommandHeader() const;

    /**
     * (package-private)<br>
     * Gets the current SV KVC
     *
     * @return The value of the current KVC
     * @since 2.0.1
     */
    uint8_t getCurrentKVC() const;

    /**
     * (package-private)<br>
     * Gets the SV transaction number
     *
     * @return The value of the SV transaction number
     * @since 2.0.1
     */
    int getTransactionNumber() const;

    /**
     * (package-private)<br>
     * Gets the SignatureLo value of the last SV transaction (reload, debit, undebit)
     *
     * @return A byte array containing the signature data
     * @since 2.0.1
     */
    const std::vector<uint8_t>& getPreviousSignatureLo() const;

    /**
     * (package-private)<br>
     * Gets the new challenge value generated by the command
     *
     * @return A byte array containing the challenge
     * @since 2.0.1
     */
    const std::vector<uint8_t>& getChallengeOut() const;

    /**
     * (package-private)<br>
     * Gets the current SV balance
     *
     * @return The value of the SV balance
     * @since 2.0.1
     */
    int getBalance() const;

    /**
     * (package-private)<br>
     * Gets a SvLoadLogRecord containing the load record <br>
     * May return null if the load record is not available (debit/undebit case for card rev &lt; 3.2)
     *
     * @return A SvLoadLogRecord object containing the log data or null
     * @since 2.0.1
     */
    const std::shared_ptr<SvLoadLogRecord> getLoadLog() const;

    /**
     * (package-private)<br>
     * Gets a {@link SvDebitLogRecord} containing the last debit record <br>
     * May return null if the debit record is not available (load case for card rev &lt; 3.2)
     *
     * @return A {@link SvDebitLogRecord} object containing the log data or null
     * @since 2.0.1
     */
    const std::shared_ptr<SvDebitLogRecord> getDebitLog() const;

    /**
     * {@inheritDoc}
     *
     * @since 2.0.1
     */
    const std::map<const int, const std::shared_ptr<StatusProperties>>& getStatusTable() const
        override;

private:
    /**
     *
     */
    const std::unique_ptr<Logger> mLogger = LoggerFactory::getLogger(typeid(CmdCardSvGet));

    /**
     * The command
     */
    static const CalypsoCardCommand mCommand;

    /**
     *
     */
    static const std::map<const int, const std::shared_ptr<StatusProperties>> STATUS_TABLE;

    /**
     *
     */
    std::vector<uint8_t> mHeader;

    /**
     *
     */
    uint8_t mCurrentKVC;

    /**
     *
     */
    int mTransactionNumber;

    /**
     *
     */
    std::vector<uint8_t> mPreviousSignatureLo;

    /**
     *
     */
    std::vector<uint8_t> mChallengeOut;

    /**
     *
     */
    int mBalance;

    /**
     *
     */
    std::shared_ptr<SvLoadLogRecord> mLoadLog;

    /**
     *
     */
    std::shared_ptr<SvDebitLogRecord> mDebitLog;

    /**
     *
     */
    static const std::map<const int, const std::shared_ptr<StatusProperties>> initStatusTable();
};

}
}
}
